---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
data:
  cloud-config: |-
    address: "ca-external-grpc-cloud-provider-service:8086"
    scale-down-delay-after-add: "1m"
    scale-down-utilization-threshold: 0.6
    # key: "/etc/ssl/client-cert/tls.key"
    # cert: "/etc/ssl/client-cert/tls.crt"
    # cacert: "/etc/ssl/client-cert/ca.crt"
