---
apiVersion: v1
kind: Service
metadata:
  name: ca-external-grpc-cloud-provider-service
  namespace: kube-system
  labels:
    app: ca-external-grpc-cloud-provider
spec:
  ports:
  - name: grpc
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: ca-external-grpc-cloud-provider
